server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3380/gym_db}
spring.datasource.username=${DB_USER:user_gym}
spring.datasource.password=${DB_PASSWORD:user_gym}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true