version: '3.8'

services:
  #   # --- EL SERVICIO 'db' LOCAL YA NO SE USA PARA EL BACKEND (USAMOS TiDB) ---
  #   db:
  #     image: mysql:8.0
  #     container_name: gym-mysql
  #     restart: always
  #     environment:
  #       MYSQL_ROOT_PASSWORD: user_gym
  #       MYSQL_DATABASE: gym_db
  #       MYSQL_USER: user_gym
  #       MYSQL_PASSWORD: user_gym
  #     ports:
  #       - "3380:3306" # Cambiamos el puerto externo (3380 en lugar de 3306) para evitar conflictos si quieres tenerlo levantado.
  #     volumes:
  #       - ./mysql-data:/var/lib/mysql

  # --- SERVICIO 2: BACKEND (CONECTADO A TiDB CLOUD) ---
  backend:
    build: ./gymapp-back
    container_name: gym-backend
    ports:
      - "8080:8080"
    # Cargamos el archivo .env donde tienes tus datos de TiDB
    env_file:
      - ./gymapp-back/.env
    environment:
      # Usamos las variables que definiste en tu .env para conectar a la nube
      # Nota: Usamos el puerto 4000 de TiDB
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/back_solutions?useSSL=true&verifyServerCertificate=true&ssl-mode=REQUIRED
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # --- SERVICIO 3: FRONTEND (React + Nginx) ---
  frontend:
    build: ./gym-frontend # Busca el Dockerfile en esta carpeta
    container_name: gym-frontend
    restart: always
    ports:
      - "80:80" # Tu app estará en http://localhost
    depends_on:
      - backend # Inicia después del back
